### ISSUE TITLE
Octokit::InvalidRepository for carrierwave

### ISSUE THREAD

**Issue by jaredbeck** [zverok/any_good#2]
This gem (any_good) is going to be helpful, thanks. :heart:

It worked for the first few gems I tried, then I got this error:

```
any_good carrierwave
.../octokit-4.8.0/lib/octokit/repository.rb:92:in `raise_invalid_repository!': 
"carrierwaveuploader/carrierwave/" is invalid as a repository identifier. 
Use the repo/user (String) format, or the repository ID (Integer), or 
a hash containing :repo and :user keys. (Octokit::InvalidRepository)
from .../octokit-4.8.0/lib/octokit/repository.rb:34:in `initialize'
from .../octokit-4.8.0/lib/octokit/repository.rb:58:in `new'
from .../octokit-4.8.0/lib/octokit/repository.rb:58:in `path'
from .../octokit-4.8.0/lib/octokit/client/repositories.rb:29:in `repository'
from .../any_good-0.0.2/lib/any_good.rb:35:in `fetch'
from .../any_good-0.0.2/exe/any_good:6:in `<top (required)>'
from .../any_good:23:in `load'
from .../any_good:23:in `<main>'
```

**Comment by zverok** [comment]
Fixed in ver.0.0.3
```
$ any_good carrierwave
           Downloads: 14,661,942
      Latest version: 2 weeks ago
             Used by: 360
               Stars: 7,854
               Forks: 1,404
         Last commit: 4 days ago
         Open issues: 50+
 ...without reaction: 34
    ...last reaction: 4 days ago
       Closed issues: 50+
      ...last closed: 4 days ago
```
